<?php
/**
 * Created by PhpStorm.
 * User: smit0015
 * Date: 7/6/2016
 * Time: 10:01 AM
 */

/**
 * @file
 * Views field handler for suma stats date options
 */

/**
 * Class suma_stats_field_option
 * Gets the date format option from a date field in suma stats
 */
class suma_stats_field_option extends views_handler_field {

//  function query() {
////    $this->field_alias = $this->real_field;
//  }
//
//  /**
//   * @return array
//   * setting the default option and definition of the field
//   * default is set to months
//   */
//  function option_definition() {
//    $options = parent::option_definition();
//    $options['date_format'] = array(
//      'default' => 'months',
//    );
//    return $options;
//  }
//
//  function options_form(&$form, &$form_state) {
//    //offer a list of options of date formats for the user
//    //to choose from
//    parent::options_form($form, $form_state);
//
//    $form['date_format'] = array(
//      '#title' => t('Date Format Options'),
//      '#type' => 'select',
//      '#default_value' => $this->options['date_format'],
//      '#options' => array(
//        'hour' => 'Hour',
//        'day' => 'Day',
//        'month' => 'Month',
//        'year' => 'Year',
//      )
//    );
//    return $form;
//  }
}
